#!/bin/bash

ONOS_DOCKER_NAME=${ONOS_DOCKER_NAME:-onos}
ONOS_IMG=${ONOS_IMG:-onosproject/onos:2.2.2}

docker run -it --rm \
  --name $ONOS_DOCKER_NAME \
  -e ONOS_APPS \
  --network host \
  --cpus=1.0 \
  --memory=4g \
  --ulimit nofile=65536:65536 \
  -v /tmp/onos:/root/onos/apache-karaf-4.2.8/data/tmp \
  $ONOS_IMG "$@"
